-- Layered space background + supernova animation for wezterm.
--
-- Loaded conditionally by ~/.wezterm.lua via `ENABLE_BACKGROUND`. Disabled by default
-- because the per-frame `set_config_overrides` cost during supernova playback noticeably
-- impacts terminal responsiveness. Re-enable when willing to keep working on perf.
--
-- Assets (generated by stdlib Python PNG writer), resolved relative to home_dir:
--   ~/.config/wezterm/backgrounds/stars.png       (star tile)
--   ~/.config/wezterm/backgrounds/nova_bright.png (bright halo)
--   ~/.config/wezterm/backgrounds/nova_void.png   (collapsed void)
--
-- Knobs / things to tune when reviving:
--   * NOVA_TRIGGER_PROB — currently a test value (0.5, rapid-fire). Production: ~0.003.
--   * status_update_interval — animation tick rate; 200ms = 5 fps.
--   * NOVA_BRIGHT_MAX / NOVA_DARK_MAX — peak opacities.
--   * NOVA_BRIGHT_SIZE / NOVA_VOID_SIZE — px size of the PNG layers at render time.
--   * config.background table below — base scene layers.
--
-- Performance ideas to try later:
--   * Skip `set_config_overrides` when computed state hasn't crossed a threshold.
--   * Use a single shader layer instead of per-tick layer mutation.
--   * Reduce or remove base-layer parallax.

local M = {}

function M.apply(config, wezterm)
  local bg_dir           = wezterm.home_dir .. '/.config/wezterm/backgrounds'
  local stars_tile       = bg_dir .. '/stars.png'
  local nova_bright_tile = bg_dir .. '/nova_bright.png'
  local nova_void_tile   = bg_dir .. '/nova_void.png'

  -- Slight cell background behind glyphs so layered visuals don't hurt legibility
  config.text_background_opacity = 0.55

  -- Base layered scene: deep-space gradient + nebula wash + tiled star field.
  -- (Previously had two more layers — off-center purple radial accent + distant star
  -- field at slower parallax — both dropped for perf.)
  config.background = {
    -- 0. Deep-space base: radial nebula glow fading to black.
    {
      source = {
        Gradient = {
          orientation = { Radial = { cx = 0.5, cy = 0.55, radius = 1.4 } },
          colors = { '#2a1450', '#150828', '#08040f', '#000000' },
        },
      },
      width = '100%', height = '100%',
      opacity = 1.0,
    },
    -- 1. Nebula wash: purple-dominant linear gradient with slow parallax.
    {
      source = {
        Gradient = {
          orientation = { Linear = { angle = -30.0 } },
          colors = { '#3d1f6f', '#28154a', '#1a0d3a', '#0a0518' },
        },
      },
      width = '120%', height = '120%',
      horizontal_align = 'Center', vertical_align = 'Middle',
      opacity = 0.45,
      attachment = { Parallax = 0.15 },
    },
    -- 2. Star field: tiled PNG with parallax.
    {
      source = { File = stars_tile },
      repeat_x = 'Repeat', repeat_y = 'Repeat',
      width = 512, height = 512,
      horizontal_offset = 128, vertical_offset = 64,
      opacity = 0.50,
      hsb = { brightness = 0.85 },
      attachment = { Parallax = 0.75 },
    },
  }

  -- ==== Supernova animation ===================================================
  -- Five phases: rise -> peak -> collapse -> void -> recover (~15s total).
  -- Driven by wezterm's update-status event, ticking every status_update_interval.
  -- ============================================================================

  config.status_update_interval = 200  -- ms; 5 fps animation tick

  local NOVA_PHASES = { rise = 4.0, peak = 3.0, collapse = 1.0, void = 5.0, recover = 2.0 }
  local NOVA_DURATION = NOVA_PHASES.rise + NOVA_PHASES.peak + NOVA_PHASES.collapse
                     + NOVA_PHASES.void + NOVA_PHASES.recover  -- 15.0 s
  local NOVA_TRIGGER_PROB = 0.5      -- TESTING value; production ~= 0.003 (one every ~33s)
  local NOVA_BRIGHT_MAX   = 0.55     -- peak opacity of the bright halo
  local NOVA_DARK_MAX     = 0.85     -- peak opacity of the void
  local NOVA_BRIGHT_SIZE  = 140      -- bright PNG size in px (fixed; size animation removed for perf)
  local NOVA_VOID_SIZE    = 100      -- void PNG size in px

  local nova = nil
  local tick = 0
  local TICK_SECONDS = config.status_update_interval / 1000

  -- Returns: bright_opacity, dark_opacity. Sizes are static.
  local function nova_state(t)
    local p = NOVA_PHASES
    if t < p.rise then return (t / p.rise) * NOVA_BRIGHT_MAX, 0 end
    t = t - p.rise
    if t < p.peak then
      local twinkle = math.sin(t * 4.0) * 0.04
      return NOVA_BRIGHT_MAX + twinkle, 0
    end
    t = t - p.peak
    if t < p.collapse then
      local f = t / p.collapse
      return (1 - f) * NOVA_BRIGHT_MAX, f * NOVA_DARK_MAX
    end
    t = t - p.collapse
    if t < p.void then return 0, NOVA_DARK_MAX end
    t = t - p.void
    if t < p.recover then return 0, (1 - t / p.recover) * NOVA_DARK_MAX end
    return 0, 0
  end

  local function nova_layers(n, t, dim)
    local bright_op, dark_op = nova_state(t)
    local layers = {}
    if bright_op > 0.01 then
      local half = math.floor(NOVA_BRIGHT_SIZE / 2)
      table.insert(layers, {
        source = { File = nova_bright_tile },
        width = NOVA_BRIGHT_SIZE, height = NOVA_BRIGHT_SIZE,
        horizontal_align = 'Left', vertical_align = 'Top',
        horizontal_offset = math.floor(n.cx * dim.pixel_width)  - half,
        vertical_offset   = math.floor(n.cy * dim.pixel_height) - half,
        repeat_x = 'NoRepeat', repeat_y = 'NoRepeat',
        opacity = bright_op,
      })
    end
    if dark_op > 0.01 then
      local half = math.floor(NOVA_VOID_SIZE / 2)
      table.insert(layers, {
        source = { File = nova_void_tile },
        width = NOVA_VOID_SIZE, height = NOVA_VOID_SIZE,
        horizontal_align = 'Left', vertical_align = 'Top',
        horizontal_offset = math.floor(n.cx * dim.pixel_width)  - half,
        vertical_offset   = math.floor(n.cy * dim.pixel_height) - half,
        repeat_x = 'NoRepeat', repeat_y = 'NoRepeat',
        opacity = dark_op,
      })
    end
    return layers
  end

  wezterm.on('update-status', function(window, _pane)
    tick = tick + 1
    local now = tick * TICK_SECONDS

    if nova == nil then
      if math.random() >= NOVA_TRIGGER_PROB then return end
      nova = {
        cx = 0.08 + math.random() * 0.84,
        cy = 0.08 + math.random() * 0.84,
        started = now,
      }
    end

    local elapsed = now - nova.started
    if elapsed >= NOVA_DURATION then
      nova = nil
      window:set_config_overrides({})  -- restore base config.background
      return
    end

    local dim = window:get_dimensions()
    if dim == nil or dim.pixel_width == 0 then return end

    local combined = {}
    for _, l in ipairs(config.background) do table.insert(combined, l) end
    for _, l in ipairs(nova_layers(nova, elapsed, dim)) do table.insert(combined, l) end
    window:set_config_overrides({ background = combined })
  end)
end

return M
